In [7]:
import numpy as np
a=np.array([[1, 2, 3], [4, 5, 6]])
print('array using list:\n',a)

array using list:
 [[1 2 3]
 [4 5 6]]


In [6]:
b=np.array((1 , 3, 2))
print('array using tuple:\n',b)

array using tuple:
 [1 3 2]


In [9]:
c=np.zeros((3, 4))
print("array created with all zeros:\n", c)

array created with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
d=np.random.random((3,3))
print('random array:\n',d)

random array:
 [[0.74055125 0.66188968 0.69069636]
 [0.08358369 0.44653342 0.66070663]
 [0.14556898 0.24808114 0.15702761]]


In [28]:
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
temp=arr[:2,:2]
temp

array([[-1. ,  2. ],
       [ 4. , -0.5]])

In [31]:
a=np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print('original array:\n',a)
print('transpose array:\n',a.T)

original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
transpose array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]
