In [3]:
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [7]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier.fit(x_train, y_train)  

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [10]:
y_pred= classifier.predict(x_test)  
print(y_pred)

[3 1 3 0 3 2 7 9 6 5 6 0 7 2 6 4 7 1 1 3 7 8 4 2 4 5 8 5 3 5 5 4 6 4 3 0 5
 7 2 7 5 5 5 5 1 9 7 4 7 1 7 1 3 8 1 0 3 6 1 0 6 3 0 8 5 8 2 1 8 7 6 7 6 6
 0 7 4 8 4 2 1 5 0 0 9 8 5 9 4 2 8 3 3 0 3 8 6 6 5 3 9 3 7 8 9 5 1 0 6 5 7
 1 2 5 5 4 0 4 3 7 1 6 0 2 4 0 0 9 0 2 0 9 6 0 1 5 4 6 2 4 4 4 6 2 6 6 4 4
 0 6 8 4 4 5 9 8 3 4 0 3 7 4 8 8 5 6 2 1 2 9 3 2 4 5 4 0 4 8 2 2 1 0 9 8 7
 9 8 0 6 6 2 0 3 2 4 3 7 4 6 0 6 5 4 0 3 9 0 7 5 9 8 9 9 0 5 7 9 0 8 4 0 2
 0 5 2 1 6 0 9 8 0 9 6 0 2 6 3 7 2 1 9 7 9 7 0 7 8 0 1 2 2 1 6 7 7 1 7 7 9
 6 5 6 4 2 7 2 2 7 4 6 9 2 1 1 0 0 9 3 3 7 7 4 5 1 1 0 4 4 9 0 3 7 7 4 4 9
 2 9 2 8 4 9 2 7 1 4 4 4 6 9 0 6 9 2 7 1 5 5 6 3 4 1 6 7 1 1 1 6 9 9 7 9 7
 4 9 5 4 5 2 5 6 7 1 5 9 4 5 0 2 3 0 9 3 4 3 1 1 4 6 8 8 8 7 0 4 4 3 1 7 4
 1 0 1 0 4 4 6 7 7 0 1 4 1 0 2 0 3 1 5 9 5 3 5 5 3 5 6 0 1 1 7 9 8 4 2 8 3
 3 7 6 2 1 4 2 1 9 4 1 3 9 0 3 3 4 3 9 5 8 6 2 1 7 8 5 7 9 9 1 4 1 2 8 8 5
 7 8 0 9 1 9 9 2 1 1 2 4 7 3 1 0 7 2 8 8 2 1 3 6 2 5 9 8 8 5 8 6 4 1 3 1 2
 1 4 6 1 6 6 0 5 1 7 8 2 

In [11]:
#Confusion Matrix and Classification report for Random Forest

In [12]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
matrix = confusion_matrix(y_test,y_pred)
print('Confusion matrix : \n',matrix)
matrix = classification_report(y_test,y_pred)
print('Classification report : \n',matrix)

Confusion matrix : 
 [[59  0  0  0  1  0  0  0  0  0]
 [ 0 57  0  0  0  1  0  0  1  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  0 49  0  0  0  0  0  0]
 [ 0  0  0  0 60  0  0  1  0  0]
 [ 0  0  2  1  1 48  0  0  0  0]
 [ 1  0  0  0  2  0 50  0  0  0]
 [ 0  2  0  0  2  0  0 53  0  0]
 [ 0  2  1  0  0  0  0  2 41  1]
 [ 0  1  0  0  0  1  0  0  1 52]]
Classification report : 
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        60
           1       0.92      0.97      0.94        59
           2       0.94      1.00      0.97        47
           3       0.98      1.00      0.99        49
           4       0.91      0.98      0.94        61
           5       0.96      0.92      0.94        52
           6       1.00      0.94      0.97        53
           7       0.95      0.93      0.94        57
           8       0.95      0.87      0.91        47
           9       0.98      0.95      0.96        55

    accuracy              